name: Build container image
description: Builds a Docker image and outputs it as a .tar file

inputs:
    image:
        description: The image name
        required: true
    tag:
        description: The tag name
        default: staging
        required: false
    context:
        description: Build context path
        default: .
        required: false

runs:
    using: "composite"
    steps:
        - name: Debug paths
          shell: bash
          run: |
              echo "Composite step is running in: $PWD"
              echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build image
          uses: docker/build-push-action@v5
          with:
              context: ${{ inputs.context }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
              tags: ${{ inputs.image }}:${{ inputs.tag }}
              load: true

        - name: Save Docker image
          shell: bash
          run: docker save -o ${GITHUB_WORKSPACE}/${{ inputs.image }}.tar ${{ inputs.image }}:${{ inputs.tag }}
