name: Build container image
description: Builds a Docker image and outputs it as a .tar file

inputs:
    image:
        description: The image name
        required: true
    tag:
        description: The tag name
        default: staging
        required: false
    context:
        description: Build context path
        default: .
        required: false

runs:
    using: "composite"
    steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
              version: latest

        - name: Build image
          uses: docker/build-push-action@v6
          with:
              context: ${{ inputs.context }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
              tags: ${{ inputs.image }}:${{ inputs.tag }}
              load: true

        - name: Save Docker image
          shell: bash
          run: docker save -o ${{ inputs.image }}.tar ${{ inputs.image }}:${{ inputs.tag }}
